import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

// Mirrors DocumentRecord (defined in @mivend/plugin-documents/src/types.ts,
// re-exported through erp-import's ImportRecord union). Only 'return' and
// 'reconciliation' are pushed via ERP — invoice/contract are generated by
// Vendure itself and never come in through this endpoint.
export class DocumentRecordDto {
    @ApiProperty({ description: 'ERP identifier, used as the idempotency key.' })
    erpId!: string;

    @ApiProperty({ enum: ['return', 'reconciliation'] })
    type!: string;

    @ApiProperty({ description: 'Must match an already-imported Counterparty erpId.' })
    counterpartyErpId!: string;

    @ApiPropertyOptional({
        type: String,
        nullable: true,
        description:
            'Vendure Order.customFields.erpOrderId, if this document is tied to a specific order.',
    })
    orderErpId?: string | null;

    @ApiProperty({ description: 'Human-readable document number, e.g. RET-000123.' })
    number!: string;

    @ApiProperty({ description: 'ISO 8601 datetime.' })
    issueDate!: string;

    @ApiPropertyOptional({
        type: Number,
        nullable: true,
        description: 'Decimal amount — converted to the smallest currency unit internally.',
    })
    amount?: number | null;

    @ApiPropertyOptional({ type: String, nullable: true, example: 'RUB' })
    currencyCode?: string | null;

    @ApiPropertyOptional({
        type: String,
        nullable: true,
        description: 'ERP-hosted file URL — this endpoint never uploads/stores the file itself.',
    })
    fileUrl?: string | null;

    @ApiPropertyOptional({
        type: 'object',
        nullable: true,
        additionalProperties: true,
        description:
            'Free-form per-type extras, e.g. { reason } for return, { periodStart, periodEnd } for reconciliation.',
    })
    metadata?: Record<string, unknown> | null;
}
