import { chromium } from '@playwright/test';
import { readFileSync } from 'node:fs';
const env=Object.fromEntries(readFileSync('/opt/mivend/apps/server/.env.central.staging-integration','utf8').split('\n').filter(l=>l.includes('=')&&!l.startsWith('#')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1360,height:1000}});
await p.goto('http://localhost:5185/login').catch(()=>{});
await p.waitForLoadState('networkidle'); await p.waitForTimeout(2500);
console.log(p.url());
await p.screenshot({path:'/tmp/claude-0/login.png'});
await p.locator('input').first().fill(env.SUPERADMIN_USERNAME);
await p.locator('input[type="password"]').fill(env.SUPERADMIN_PASSWORD);
await p.locator('button[type="submit"]').click();
await p.waitForTimeout(4000);
await p.goto('http://localhost:5185/global-settings');
await p.waitForTimeout(4000);
console.log(p.url());
await p.screenshot({path:'/tmp/claude-0/-opt-mivend/2c47e495-aa81-46dd-bfba-8a4289a19e67/scratchpad/checkbox.png'});
await b.close();
