export { AccessControlPlugin } from './src/access-control.plugin';
export { CustomPermission } from './src/custom-permission';
export { AccessScopeService } from './src/access-scope.service';
export { RoleScopeConfigService } from './src/role-scope-config.service';
export type { AccessScopeConfig } from './src/role-scope-config.service';
export { RoleAccessScope } from './src/entities/role-access-scope.entity';
export { Department } from './src/entities/department.entity';
export { DepartmentService } from './src/department.service';
export type { DepartmentRecordInput } from './src/department.service';
export { Branch } from './src/entities/branch.entity';
export { BranchService } from './src/branch.service';
export type { BranchRecordInput } from './src/branch.service';
export { EmployeeService } from './src/employee.service';
export type { EmployeeRecordInput } from './src/employee.service';
export { CreditTermLimit } from './src/entities/credit-term-limit.entity';
export { CreditTermLimitService } from './src/credit-term-limit.service';
export type { AccessScope, AccessScopeKind } from './src/types';
