import { describe, expect, it } from 'vitest';

import { REPLAYABLE_AGGREGATE_TYPES, streamToAggregateType } from '../../stream-aggregate-type';
import { ALL_INBOUND_STREAMS } from '../../types';

describe('streamToAggregateType', () => {
    it.each([
        ['price-type', 'priceType'],
        ['counterparty-credit-balance', 'counterpartyCreditBalance'],
        ['order-registration-result', 'orderRegistrationResult'],
        ['product-photo', 'productPhoto'],
        ['bank-account', 'bankAccount'],
    ] as const)('%s -> %s', (stream, aggregateType) => {
        expect(streamToAggregateType(stream)).toBe(aggregateType);
    });

    it('offers no replay for vat-rate (generated by Integration Service itself)', () => {
        expect(streamToAggregateType('vat-rate')).toBeNull();
    });

    it('every consumed stream is either replayable or deliberately excluded', () => {
        const unmapped = ALL_INBOUND_STREAMS.filter(s => streamToAggregateType(s) === null);
        expect(unmapped).toEqual(['vat-rate']);
        for (const stream of ALL_INBOUND_STREAMS) {
            const type = streamToAggregateType(stream);
            if (type) expect(REPLAYABLE_AGGREGATE_TYPES).toContain(type);
        }
    });
});
