import type { InboundStream } from './types';

// aggregateTypes accepted by Integration Service's POST /api/resync/v1/replay (its
// INGESTION_ENTITY_TYPES): replay is only offered for streams that map onto one of them.
export const REPLAYABLE_AGGREGATE_TYPES: readonly string[] = [
    'category',
    'manufacturer',
    'organization',
    'warehouse',
    'priceType',
    'product',
    'productPhoto',
    'offer',
    'price',
    'stock',
    'stockOrganization',
    'storageLocation',
    'unit',
    'counterparty',
    'counterpartyCreditBalance',
    'contract',
    'department',
    'position',
    'region',
    'legalForm',
    'user',
    'pointOfSale',
    'bank',
    'bankAccount',
    'discountRule',
    'retroBonusRule',
    'grantedDiscount',
    'grantedRetroBonus',
    'promoRule',
    'orderRegistrationResult',
    'orderChanged',
];

// vat-rate is generated by Integration Service itself and needs a different sourceSystem, which
// the replay client does not send: no replay for it.
export function streamToAggregateType(stream: InboundStream): string | null {
    const camel = stream.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase());
    return REPLAYABLE_AGGREGATE_TYPES.includes(camel) ? camel : null;
}
